### ISSUE TITLE
Class for no border

### ISSUE THREAD

**Issue by lachlanjc** [basscss/borders#1]
It'd be great to have a class for removing the border (probably with `border-width` set to `0`).

**Comment by jxnblk** [comment]
Not opposed to the idea but what would the use-case be?

**Comment by lachlanjc** [comment]
With either inherited styles (not in my case, but often people have more than one framework), or browser defaults, some elements get a border that just looks awful. Having a class built right in would be useful.





On Wednesday, Feb 18, 2015 at 17:02, Brent Jackson <notifications@github.com>, wrote:

Not opposed to the idea but what would the use-case be?

**Comment by jxnblk** [comment]
I've actually added `.no-border` to the beta version, which will be part of Basscss v7. https://github.com/basscss/borders/blob/master/index.css#L33

**Comment by lachlanjc** [comment]
👍
